export const ALL_DESCRIPTIONS = [
    {  description: 'clear sky' },
    {  description: 'few clouds' },
    {  description: 'scattered clouds' },
    {  description: 'broken clouds' },
    {  description: 'overcast clouds' },
    {  description: 'shower rain' },
    {  description: 'light intensity drizzle' },
    {  description: 'drizzle' },
    {  description: 'heavy intensity drizzle' },
    {  description: 'light intensity drizzle rain' },
    {  description: 'drizzle rain' },
    {  description: 'heavy intensity drizzle rain' },
    {  description: 'shower rain and drizzle' },
    {  description: 'heavy shower rain and drizzle' },
    {  description: 'shower drizzle' },
    {  description: 'light intensity shower rain' },
    {  description: 'shower rain' },
    {  description: 'heavy intensity shower rain' },
    {  description: 'ragged shower rain' },
    {  description: 'rain' },
    {  description: 'light rain' },
    {  description: 'moderate rain' },
    {  description: 'heavy intensity rain' },
    {  description: 'very heavy rain' },
    {  description: 'extreme rain' },
    {  description: 'thunderstorm' },
    {  description: 'thunderstorm with light rain' },
    {  description: 'thunderstorm with rain' },
    {  description: 'thunderstorm with heavy rain' },
    {  description: 'light thunderstorm' },
    {  description: 'heavy thunderstorm' },
    {  description: 'ragged thunderstorm' },
    {  description: 'thunderstorm with light drizzle' },
    {  description: 'thunderstorm with drizzle' },
    {  description: 'thunderstorm with heavy drizzle' },
    {  description: 'snow' },
    {  description: 'freezing rain' },
    {  description: 'light snow' },
    {  description: 'Snow' },
    {  description: 'Heavy snow' },
    {  description: 'Sleet' },
    {  description: 'Light shower sleet' },
    {  description: 'Light rain and snow' },
    {  description: 'Rain and snow' },
    {  description: 'Light shower snow' },
    {  description: 'Shower snow' },
    {  description: 'Heavy shower snow' },
    {  description: 'mist' },
    {  description: 'Smoke' },
    {  description: 'Haze' },
    {  description: 'sand/ dust whirls' },
    {  description: 'fog' },
    {  description: 'sand' },
    {  description: 'dust' },
    {  description: 'volcanic ash' },
    {  description: 'squalls' },
    {  description: 'tornado' },
  ];
  